apiVersion: v1
kind: Secret
metadata:
name: db-credentials-secret
type: Opaque
data:

# All values must be base64 encoded
To encode: echo -n 'your_db_user' | base64
DB_USER: "eW91cl9kYl91c2Vy"
DB_PASSWORD: "eW91cl9kYl9wYXNzd29yZA=="
